name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo install just --version 1.46.0 --locked
      - run: just release-check
        env:
          REGISTRY_ROOT_PUBLIC: ed4928c628d1c2c6eae90338905995612959273a5c63f93636c14614ac8737d1
